// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVcVqj_kim9Y3kwyRLyH9C-OdObArINnA',
    appId: '1:1053785611323:web:bf3af294ea7e944777901e',
    messagingSenderId: '1053785611323',
    projectId: 'smartplant-446b0',
    authDomain: 'smartplant-446b0.firebaseapp.com',
    storageBucket: 'smartplant-446b0.firebasestorage.app',
    measurementId: 'G-71YQ2F45Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMse1qSPnIvIBigohWVZSOPjQRogw2sTs',
    appId: '1:1053785611323:android:af932d8c800f66b377901e',
    messagingSenderId: '1053785611323',
    projectId: 'smartplant-446b0',
    storageBucket: 'smartplant-446b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaJpKA2hzpsFhm7pL2BNWsS9vR7TSFgI4',
    appId: '1:1053785611323:ios:a2b387774399bbc977901e',
    messagingSenderId: '1053785611323',
    projectId: 'smartplant-446b0',
    storageBucket: 'smartplant-446b0.firebasestorage.app',
    iosBundleId: 'com.example.mobappgrad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaJpKA2hzpsFhm7pL2BNWsS9vR7TSFgI4',
    appId: '1:1053785611323:ios:a2b387774399bbc977901e',
    messagingSenderId: '1053785611323',
    projectId: 'smartplant-446b0',
    storageBucket: 'smartplant-446b0.firebasestorage.app',
    iosBundleId: 'com.example.mobappgrad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVcVqj_kim9Y3kwyRLyH9C-OdObArINnA',
    appId: '1:1053785611323:web:113675f9f8f3118277901e',
    messagingSenderId: '1053785611323',
    projectId: 'smartplant-446b0',
    authDomain: 'smartplant-446b0.firebaseapp.com',
    storageBucket: 'smartplant-446b0.firebasestorage.app',
    measurementId: 'G-Q42RGNLHZR',
  );
}
